pipeline{

    agent any

    parameters{
        string(name: 'SPEC', defaultValue: "cypress/e2e/spec/**", description: "Enter the script that you want to run")
        choice(name: 'BROWSER', choices: ['chrome', 'edge', 'firefox'], description: "Choose the browser where you want to execute the tests")
    }

    options{
            ansiColor('xterm')
    }

    stages{
        stage('Building'){
            steps{
                echo "Building the application stage (I got no application to build in this project)"
            }
        }
        stage('Testing'){
            steps{
                bat "npm i"
                bat "npx cypress run --browser ${BROWSER} --spec ${SPEC}"
            }
        }
        stage('Deploying'){
            steps{
                echo "For the deployment of the application"
            }
        }

    }
    post{
            always{
                publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'E:\Codes\planit\cypress\reports', reportFiles: 'test_report.html', reportName: 'HTML Report', reportTitles: '', useWrapperFileDirectly: true])
            }
    }
}